### PR TITLE
Geohashes geospatial tags

### PR DESCRIPTION
**Pull request by kevin-bruhwiler**
I don't seem to be able to connect to the mongodb (I've made sure it's running) so we might want to look in to that.

### CODE REVIEW

**Comment by kevin-bruhwiler** [comment]
Also you still need to add everybody as a collaborator, since we can't merge pull requests otherwise.

**Comment by GrEedWish** [comment]
Could you check your email, since I have sent you all invitation as group members instead of collaborator?

**Comment by GrEedWish** [comment]
The MongoDB is running on dover, could you try 'mongo' on dover?

**Comment by kevin-bruhwiler** [comment]
It is indeed working on dover, and so is my geohash thing. Also, you did send an email. Sorry, missed that somehow.

**Comment by kevin-bruhwiler** [comment]
I still can't merge this though. Probably because I wasn't a member when I made it.

**Comment by GrEedWish** [comment]
Have you received the email yet?

**Comment by GrEedWish** [comment]
I will set up a new pull request and lets try to merge it as a member?

**Comment by GrEedWish** [comment]
Thank you, I think it is good to merge now.

**Pull request merged**
